service: jiraTagger

frameworkVersion: ">=1.28.0 <2.0.0"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

custom: ${file(./config.json)}

provider:
  name: aws
  cfLogs: true
  runtime: go1.x
  stage: ${opt:stage, self:custom.env}
  region: us-east-1
  memorySize: 128
  stackTags:
    squad: Test

plugins:
 - serverless-offline

functions:
  receive:
    handler: bin/receive
    events:
      - http:
          path: receive
          method: post
          cors: true
      - http:
          path: receive
          method: get
          cors: true
